### ISSUE TITLE
Can't see all items in settings list view

### ISSUE THREAD

**Issue by mohlerm** [micku7zu/Locate-driver#1]
Hi,

In the _settings_ part of the app I can not see all items, in particular the last one.
It's probably easier to provide a screenshot:
<img src="https://i.imgur.com/aOeODHS.jpg" width="400">
As you can see after forth message it cuts off. It sometimes displays a scroll bar on the right side but I do not seem to be able to scroll.

I use a Sony Z3Compact with Android 6.0.
Display resolution is 720x1280

**Comment by micku7zu** [comment]
I will fix it after vacation. In 16th Jully will be back home

**Comment by micku7zu** [comment]
Fixed in b8ea5ff6907309275e1d8830c68343e25b98ca2a. Closed. Will be available on next release.
